default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_login

development:
  <<: *default

production:
  <<: *default
  host: dpg-ck0prkhjbtgs73cfdff0-a
  database: s_original_05ln
  username: s_original_05ln_user
  password: aQz3bP9kqSkhzxgaUfd3vwAgvpOa2WLa